logging:
  level:
    by.tms.lesson45_task1: DEBUG
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shop
    username: root
    password: root

  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 1MB

